# Generated by Django 3.0.8 on 2020-07-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdRecords', '0002_auto_20200727_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('image_description', models.CharField(max_length=255)),
                ('image_uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('text_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('text_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
