# Generated by Django 3.0.8 on 2020-07-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200727_1427'),
        ('AdRecords', '0003_auto_20200728_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text_property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userProfile'),
        ),
    ]
