# Generated by Django 3.0.8 on 2020-07-30 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200727_1427'),
        ('AdRecords', '0006_auto_20200728_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_property_id', to='accounts.userProfile'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text_property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_property_id', to='accounts.userProfile'),
        ),
    ]
