# Generated by Django 3.0.8 on 2020-07-27 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200727_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_joined',
            new_name='date_joined_for_user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_organizer',
            new_name='user_is_organizer',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='user_location',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='updated_on',
            new_name='user_profile_updated_on',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined_for_customer', models.DateTimeField(auto_now_add=True)),
                ('company_profile_updated_on', models.DateTimeField(auto_now=True)),
                ('company_is_organizer', models.BooleanField(default=False)),
                ('company_location', models.CharField(blank=True, max_length=30)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
